name: Build Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'
    
jobs:
  Test-Examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mlek-cmsis-pack-examples
        uses: actions/checkout@v4

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build projects
        run:  cbuild mlek.csolution.yml --packs --context kws.Release+AVH-SSE-300-U55

      - name: Upload Artifact without --update-rte
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: NoUpdateRTE
          path: |
            ./out
          retention-days: 1
          
      - name: Build projects
        if: always()
        run:  cbuild mlek.csolution.yml --update-rte --packs --context kws.Release+AVH-SSE-300-U55

      - name: Upload Artifact with --update-rte
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: UpdateRTE
          path: |
            ./out
          retention-days: 1
