name: Build Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'
    
jobs:
  Test-Examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mlek-cmsis-pack-examples
        uses: actions/checkout@v4

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build projects
        run:  cbuild mlek.csolution.yml --packs --rebuild --toolchain AC6
